version: "3"

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
